/*
 * This source file was generated by the Gradle 'init' task
 */
package by.gstu.project.app;

import by.gstu.project.list.LinkedList;

import static by.gstu.project.utilities.StringUtils.join;
import static by.gstu.project.utilities.StringUtils.split;
import static by.gstu.project.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
